#!/home/coldbrewrosh/.nix-profile/bin/zsh
DEVICE_ID=14
STATE=$(xinput list-props "$DEVICE_ID" | grep "Device Enabled" | awk '{print $4}')

if [ "$STATE" -eq 1 ]; then
    xinput disable "$DEVICE_ID"
else
    xinput enable "$DEVICE_ID"
fi
